### PR TITLE
Improve MFM, add instructions

### LINKED ISSUE #5: Setup guide
The setup instructions are very unclear, like what `i` is supposed to be, the format everything should be on respective websites, etc. I'm trying to make a PR to fix formatting MFM but it's very hard to set the bot up.

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
- Improve/Fix MFM formatting
- Instructions (closes #5 )
- Small message when ready

Demo at https://stop.voring.me/@testbot

### CODE REVIEW

**Comment by syuilo** [comment]
Thanks!

**Comment by ThatOneCalculator** [comment]
@syuilo no problem! :) 

Will the @repo@misskey.io bot be updated soon with the new ver?

**Comment by syuilo** [comment]
I do not know as I do not manage that account 😌

**Comment by ThatOneCalculator** [comment]
Oh! I thought you did, my bad ^^" Do you know who does?

**Pull request merged**
